prompt --application/deployment/install/install_tabele_sql
begin
--   Manifest
--     INSTALL: INSTALL-tabele.sql
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.10.07'
,p_release=>'22.2.0'
,p_default_workspace_id=>25142937697737223804
,p_default_application_id=>23067
,p_default_id_offset=>0
,p_default_owner=>'WKSP_MYSZARD'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(41115099147698084569)
,p_install_id=>wwv_flow_imp.id(37088097327174612384)
,p_name=>'tabele.sql'
,p_sequence=>10
,p_script_type=>'INSTALL'
,p_script_option=>'TABLE'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'CREATE TABLE "KLIENCI" ',
'   (	"ID_KLIENTA" NUMBER(*,0) NOT NULL ENABLE, ',
'	"NAZWISKO" VARCHAR2(45 CHAR) NOT NULL ENABLE, ',
'	"IMIE" VARCHAR2(45 CHAR) NOT NULL ENABLE, ',
'	"NIP" VARCHAR2(13 CHAR), ',
'	"NUMER_KONTA" VARCHAR2(26), ',
'	"EMAIL" VARCHAR2(45 CHAR) NOT NULL ENABLE, ',
'	"POTWIERDZONY_MAIL" VARCHAR2(12), ',
'	"HASLO" VARCHAR2(45 CHAR) NOT NULL ENABLE, ',
'	"RABAT" NUMBER, ',
'	"PUNKTY" NUMBER, ',
'	"KOD_POCZTOWY" VARCHAR2(6) NOT NULL ENABLE, ',
'	"MIEJSCOWOSC" VARCHAR2(60) NOT NULL ENABLE, ',
'	"ULICA" VARCHAR2(60), ',
'	"NUMER__DOMU" VARCHAR2(10) NOT NULL ENABLE, ',
'	"DARMOWA_DOSTAWA" VARCHAR2(3), ',
'	"ROLA_UZYTKOWNIKA" VARCHAR2(5) DEFAULT ''user'', ',
'	 CONSTRAINT "KLIENCI_PK" PRIMARY KEY ("ID_KLIENTA")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "ZAMOWIENIA" ',
'   (	"ID_ZAMOWIENIA" NUMBER(*,0) NOT NULL ENABLE, ',
'	"KLIENT" NUMBER(*,0) NOT NULL ENABLE, ',
'	"NALEZNOSC" NUMBER, ',
'	"DATA_ZAMOWIENIA" DATE NOT NULL ENABLE, ',
'	"ZWROT" VARCHAR2(3 CHAR) DEFAULT ''NIE'', ',
'	 CONSTRAINT "ZAMOWIENIA_PK" PRIMARY KEY ("ID_ZAMOWIENIA")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "STANOWISKO" ',
'   (	"ID_STANOWISKA" NUMBER(*,0) NOT NULL ENABLE, ',
'	"NAZWA" VARCHAR2(45 CHAR) NOT NULL ENABLE, ',
'	"PLACA" NUMBER NOT NULL ENABLE, ',
'	 CONSTRAINT "STANOWISKO_PK" PRIMARY KEY ("ID_STANOWISKA")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "PRACOWNICY" ',
'   (	"PESEL" NUMBER(*,0) NOT NULL ENABLE, ',
'	"NAZWISKO" VARCHAR2(45 CHAR) NOT NULL ENABLE, ',
'	"IMIE" VARCHAR2(45 CHAR) NOT NULL ENABLE, ',
'	"STANOWISKO" NUMBER(*,0) NOT NULL ENABLE, ',
'	"CZAS_PRACY" NUMBER(4,2) NOT NULL ENABLE, ',
'	"DNI_URLOPU" NUMBER(4,2) NOT NULL ENABLE, ',
'	"KOD_POCZTOWY" VARCHAR2(6) NOT NULL ENABLE, ',
'	"MIEJSCOWOSC" VARCHAR2(60) NOT NULL ENABLE, ',
'	"ULICA" VARCHAR2(60), ',
'	"NUMER_DOMU" VARCHAR2(10) NOT NULL ENABLE, ',
'	"WYKORZYSTANY_URLOP" DATE, ',
'	 CONSTRAINT "PRACOWNICY_PK" PRIMARY KEY ("PESEL")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "KATEGORIA" ',
'   (	"KATEGORIA" NUMBER(*,0) NOT NULL ENABLE, ',
'	"NAZWA_KATEGORII" VARCHAR2(80 CHAR) NOT NULL ENABLE, ',
'	 CONSTRAINT "KATEGORIA_PK" PRIMARY KEY ("KATEGORIA")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "DOSTAWCY" ',
'   (	"NIP" VARCHAR2(13 CHAR) NOT NULL ENABLE, ',
'	"NUMER_KONTA" VARCHAR2(26 CHAR) NOT NULL ENABLE, ',
'	"NAZWA_DOSTAWCY" VARCHAR2(60 CHAR) NOT NULL ENABLE, ',
'	"LOKALIZACJA" VARCHAR2(45 CHAR) NOT NULL ENABLE, ',
'	"REGON" NUMBER NOT NULL ENABLE, ',
'	 CONSTRAINT "DOSTAWCY_PK" PRIMARY KEY ("NIP")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "ARTYKULY" ',
'   (	"ID_ARTYKULU" NUMBER(*,0) NOT NULL ENABLE, ',
'	"KATEGORIA" NUMBER(*,0) NOT NULL ENABLE, ',
'	"NAZWA_ARTYKULU" VARCHAR2(45 CHAR) NOT NULL ENABLE, ',
'	"PRODUCENT" VARCHAR2(60 CHAR) NOT NULL ENABLE, ',
'	"NIP_DOSTAWCY" VARCHAR2(13 CHAR) NOT NULL ENABLE, ',
'	"CENA_JEDNOSTKOWA" NUMBER NOT NULL ENABLE, ',
'	"ILOSC_MAGAZYN" NUMBER NOT NULL ENABLE, ',
'	"STATUS_PRODUKTU" VARCHAR2(20) NOT NULL ENABLE, ',
'	"OUTLET" VARCHAR2(3 CHAR) NOT NULL ENABLE, ',
'	"ZDJECIE_PRODUKTU" BLOB, ',
'	"ZDJECIE_PRODUKTU_NAZWA" BLOB, ',
'	 CONSTRAINT "TOWARY_PK" PRIMARY KEY ("ID_ARTYKULU")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "SZCZEGOLY_ZAMOWIENIA" ',
'   (	"ZAMOWIENIE" NUMBER(*,0) NOT NULL ENABLE, ',
'	"ARTYKUL" NUMBER(*,0) NOT NULL ENABLE, ',
'	"ILOSC_ZAMOWIONYCH_SZTUK" NUMBER NOT NULL ENABLE, ',
'	"VAT" NUMBER, ',
'	"FORMA_ZAMOWIENIA" VARCHAR2(60) NOT NULL ENABLE',
'   ) ;',
'',
'CREATE TABLE "ZAMOWIENIA_DOSTAWCY" ',
'   (	"ID_ZAMOWIENIA_DOSTAWCY" NUMBER NOT NULL ENABLE, ',
'	"NIP_DOSTAWCY" VARCHAR2(13) NOT NULL ENABLE, ',
'	"PESEL_PRACOWNIKA" NUMBER(*,0) NOT NULL ENABLE, ',
'	"NALEZNOSC" NUMBER NOT NULL ENABLE, ',
'	"DATA_ZAMOWIENIA" DATE NOT NULL ENABLE, ',
'	 CONSTRAINT "ZAM_DOST_PK" PRIMARY KEY ("ID_ZAMOWIENIA_DOSTAWCY")',
'  USING INDEX  ENABLE',
'   ) ;',
'',
'CREATE TABLE "SZCZEGOLY_ZAMOWIENIA_DOSTAWCY" ',
'   (	"ZAMOWIENIE_DOSTAWCA" NUMBER(*,0) NOT NULL ENABLE, ',
'	"ARTYKUL_DOSTAWCA" NUMBER(*,0) NOT NULL ENABLE, ',
'	"ILOSC_ZAMOWIONYCH_SZTUK" NUMBER NOT NULL ENABLE, ',
'	"VAT" NUMBER, ',
'	"CENA" NUMBER NOT NULL ENABLE',
'   ) ;',
'',
'CREATE TABLE "HTMLDB_PLAN_TABLE" ',
'   (	"STATEMENT_ID" VARCHAR2(30), ',
'	"PLAN_ID" NUMBER, ',
'	"TIMESTAMP" DATE, ',
'	"REMARKS" VARCHAR2(4000), ',
'	"OPERATION" VARCHAR2(30), ',
'	"OPTIONS" VARCHAR2(255), ',
'	"OBJECT_NODE" VARCHAR2(128), ',
'	"OBJECT_OWNER" VARCHAR2(128), ',
'	"OBJECT_NAME" VARCHAR2(128), ',
'	"OBJECT_ALIAS" VARCHAR2(261), ',
'	"OBJECT_INSTANCE" NUMBER(*,0), ',
'	"OBJECT_TYPE" VARCHAR2(128), ',
'	"OPTIMIZER" VARCHAR2(255), ',
'	"SEARCH_COLUMNS" NUMBER, ',
'	"ID" NUMBER(*,0), ',
'	"PARENT_ID" NUMBER(*,0), ',
'	"DEPTH" NUMBER(*,0), ',
'	"POSITION" NUMBER(*,0), ',
'	"COST" NUMBER(*,0), ',
'	"CARDINALITY" NUMBER(*,0), ',
'	"BYTES" NUMBER(*,0), ',
'	"OTHER_TAG" VARCHAR2(255), ',
'	"PARTITION_START" VARCHAR2(255), ',
'	"PARTITION_STOP" VARCHAR2(255), ',
'	"PARTITION_ID" NUMBER(*,0), ',
'	"OTHER" LONG, ',
'	"DISTRIBUTION" VARCHAR2(30), ',
'	"CPU_COST" NUMBER(*,0), ',
'	"IO_COST" NUMBER(*,0), ',
'	"TEMP_SPACE" NUMBER(*,0), ',
'	"ACCESS_PREDICATES" VARCHAR2(4000), ',
'	"FILTER_PREDICATES" VARCHAR2(4000), ',
'	"PROJECTION" VARCHAR2(4000), ',
'	"TIME" NUMBER(*,0), ',
'	"QBLOCK_NAME" VARCHAR2(128)',
'   ) ;',
'',
'ALTER TABLE "SZCZEGOLY_ZAMOWIENIA" ADD CONSTRAINT "ARTYKULY_FK" FOREIGN KEY ("ARTYKUL")',
'	  REFERENCES "ARTYKULY" ("ID_ARTYKULU") ENABLE;',
'',
'ALTER TABLE "PRACOWNICY" ADD CONSTRAINT "PRACOWNICY_STANOWISKO_FK" FOREIGN KEY ("STANOWISKO")',
'	  REFERENCES "STANOWISKO" ("ID_STANOWISKA") ENABLE;',
'',
'ALTER TABLE "SZCZEGOLY_ZAMOWIENIA_DOSTAWCY" ADD CONSTRAINT "S_ARTYKULY_DOST_FK" FOREIGN KEY ("ARTYKUL_DOSTAWCA")',
'	  REFERENCES "ARTYKULY" ("ID_ARTYKULU") ENABLE;',
'',
'ALTER TABLE "SZCZEGOLY_ZAMOWIENIA_DOSTAWCY" ADD CONSTRAINT "S_ZAMOWIENIA_DOST_FK" FOREIGN KEY ("ZAMOWIENIE_DOSTAWCA")',
'	  REFERENCES "ZAMOWIENIA_DOSTAWCY" ("ID_ZAMOWIENIA_DOSTAWCY") ENABLE;',
'',
'ALTER TABLE "ARTYKULY" ADD CONSTRAINT "TOWARY_DOSTAWCY_FK" FOREIGN KEY ("NIP_DOSTAWCY")',
'	  REFERENCES "DOSTAWCY" ("NIP") ENABLE;',
'',
'ALTER TABLE "ARTYKULY" ADD CONSTRAINT "TOWARY_KATEGORIA_FK" FOREIGN KEY ("KATEGORIA")',
'	  REFERENCES "KATEGORIA" ("KATEGORIA") ENABLE;',
'',
'ALTER TABLE "ZAMOWIENIA_DOSTAWCY" ADD CONSTRAINT "ZAMOWIENIADOST_PRACOWNICY_FK" FOREIGN KEY ("PESEL_PRACOWNIKA")',
'	  REFERENCES "PRACOWNICY" ("PESEL") ENABLE;',
'',
'ALTER TABLE "ZAMOWIENIA_DOSTAWCY" ADD CONSTRAINT "ZAMOWIENIA_DOSTAWCY_FK" FOREIGN KEY ("NIP_DOSTAWCY")',
'	  REFERENCES "DOSTAWCY" ("NIP") ENABLE;',
'',
'ALTER TABLE "SZCZEGOLY_ZAMOWIENIA" ADD CONSTRAINT "ZAMOWIENIA_FK" FOREIGN KEY ("ZAMOWIENIE")',
'	  REFERENCES "ZAMOWIENIA" ("ID_ZAMOWIENIA") ENABLE;',
'',
'ALTER TABLE "ZAMOWIENIA" ADD CONSTRAINT "ZAMOWIENIA_KLIENCI_FK" FOREIGN KEY ("KLIENT")',
'	  REFERENCES "KLIENCI" ("ID_KLIENTA") ENABLE;',
'',
''))
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(41115099226821084572)
,p_script_id=>wwv_flow_imp.id(41115099147698084569)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'ARTYKULY'
,p_last_updated_by=>'MACIEKZAK550@GMAIL.COM'
,p_last_updated_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
,p_created_by=>'MACIEKZAK550@GMAIL.COM'
,p_created_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(41115099412789084573)
,p_script_id=>wwv_flow_imp.id(41115099147698084569)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'DOSTAWCY'
,p_last_updated_by=>'MACIEKZAK550@GMAIL.COM'
,p_last_updated_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
,p_created_by=>'MACIEKZAK550@GMAIL.COM'
,p_created_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(41115099698454084574)
,p_script_id=>wwv_flow_imp.id(41115099147698084569)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'HTMLDB_PLAN_TABLE'
,p_last_updated_by=>'MACIEKZAK550@GMAIL.COM'
,p_last_updated_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
,p_created_by=>'MACIEKZAK550@GMAIL.COM'
,p_created_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(41115099856506084574)
,p_script_id=>wwv_flow_imp.id(41115099147698084569)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'KATEGORIA'
,p_last_updated_by=>'MACIEKZAK550@GMAIL.COM'
,p_last_updated_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
,p_created_by=>'MACIEKZAK550@GMAIL.COM'
,p_created_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(41115100056653084574)
,p_script_id=>wwv_flow_imp.id(41115099147698084569)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'KLIENCI'
,p_last_updated_by=>'MACIEKZAK550@GMAIL.COM'
,p_last_updated_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
,p_created_by=>'MACIEKZAK550@GMAIL.COM'
,p_created_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(41115100224755084574)
,p_script_id=>wwv_flow_imp.id(41115099147698084569)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'PRACOWNICY'
,p_last_updated_by=>'MACIEKZAK550@GMAIL.COM'
,p_last_updated_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
,p_created_by=>'MACIEKZAK550@GMAIL.COM'
,p_created_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(41115100478466084574)
,p_script_id=>wwv_flow_imp.id(41115099147698084569)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'STANOWISKO'
,p_last_updated_by=>'MACIEKZAK550@GMAIL.COM'
,p_last_updated_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
,p_created_by=>'MACIEKZAK550@GMAIL.COM'
,p_created_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(41115100675515084574)
,p_script_id=>wwv_flow_imp.id(41115099147698084569)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'SZCZEGOLY_ZAMOWIENIA'
,p_last_updated_by=>'MACIEKZAK550@GMAIL.COM'
,p_last_updated_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
,p_created_by=>'MACIEKZAK550@GMAIL.COM'
,p_created_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(41115100828707084574)
,p_script_id=>wwv_flow_imp.id(41115099147698084569)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'SZCZEGOLY_ZAMOWIENIA_DOSTAWCY'
,p_last_updated_by=>'MACIEKZAK550@GMAIL.COM'
,p_last_updated_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
,p_created_by=>'MACIEKZAK550@GMAIL.COM'
,p_created_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(41115101084639084574)
,p_script_id=>wwv_flow_imp.id(41115099147698084569)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'ZAMOWIENIA'
,p_last_updated_by=>'MACIEKZAK550@GMAIL.COM'
,p_last_updated_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
,p_created_by=>'MACIEKZAK550@GMAIL.COM'
,p_created_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(41115101294268084575)
,p_script_id=>wwv_flow_imp.id(41115099147698084569)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'ZAMOWIENIA_DOSTAWCY'
,p_last_updated_by=>'MACIEKZAK550@GMAIL.COM'
,p_last_updated_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
,p_created_by=>'MACIEKZAK550@GMAIL.COM'
,p_created_on=>to_date('20230116181308','YYYYMMDDHH24MISS')
);
wwv_flow_imp.component_end;
end;
/
