CREATE UNIQUE INDEX  "DOSTAWCY_PK" ON  "DOSTAWCY" ("NIP")
/

CREATE UNIQUE INDEX  "KATEGORIA_PK" ON  "KATEGORIA" ("KATEGORIA")
/

CREATE UNIQUE INDEX  "KLIENCI_PK" ON  "KLIENCI" ("ID_KLIENTA")
/

CREATE UNIQUE INDEX  "PRACOWNICY_PK" ON  "PRACOWNICY" ("PESEL")
/

CREATE UNIQUE INDEX  "STANOWISKO_PK" ON  "STANOWISKO" ("ID_STANOWISKA")
/

CREATE UNIQUE INDEX  "SYS_IL0160553989C00010$$" ON  "ARTYKULY" (
/

CREATE UNIQUE INDEX  "SYS_IL0160553989C00011$$" ON  "ARTYKULY" (
/

CREATE UNIQUE INDEX  "TOWARY_PK" ON  "ARTYKULY" ("ID_ARTYKULU")
/

CREATE UNIQUE INDEX  "ZAMOWIENIA_PK" ON  "ZAMOWIENIA" ("ID_ZAMOWIENIA")
/

CREATE UNIQUE INDEX  "ZAM_DOST_PK" ON  "ZAMOWIENIA_DOSTAWCY" ("ID_ZAMOWIENIA_DOSTAWCY")
/