CREATE TABLE  "KLIENCI" 
   (	"ID_KLIENTA" NUMBER(*,0) NOT NULL ENABLE, 
	"NAZWISKO" VARCHAR2(45 CHAR) NOT NULL ENABLE, 
	"IMIE" VARCHAR2(45 CHAR) NOT NULL ENABLE, 
	"NIP" VARCHAR2(13 CHAR), 
	"NUMER_KONTA" VARCHAR2(26), 
	"EMAIL" VARCHAR2(45 CHAR) NOT NULL ENABLE, 
	"POTWIERDZONY_MAIL" VARCHAR2(12), 
	"HASLO" VARCHAR2(45 CHAR) NOT NULL ENABLE, 
	"RABAT" NUMBER, 
	"PUNKTY" NUMBER, 
	"KOD_POCZTOWY" VARCHAR2(6) NOT NULL ENABLE, 
	"MIEJSCOWOSC" VARCHAR2(60) NOT NULL ENABLE, 
	"ULICA" VARCHAR2(60), 
	"NUMER__DOMU" VARCHAR2(10) NOT NULL ENABLE, 
	"DARMOWA_DOSTAWA" VARCHAR2(3), 
	"ROLA_UZYTKOWNIKA" VARCHAR2(5) DEFAULT 'user', 
	 CONSTRAINT "KLIENCI_PK" PRIMARY KEY ("ID_KLIENTA")
  USING INDEX  ENABLE
   )
/

CREATE TABLE  "ARTYKULY" 
   (	"ID_ARTYKULU" NUMBER(*,0) NOT NULL ENABLE, 
	"KATEGORIA" NUMBER(*,0) NOT NULL ENABLE, 
	"NAZWA_ARTYKULU" VARCHAR2(45 CHAR) NOT NULL ENABLE, 
	"PRODUCENT" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"NIP_DOSTAWCY" VARCHAR2(13 CHAR) NOT NULL ENABLE, 
	"CENA_JEDNOSTKOWA" NUMBER NOT NULL ENABLE, 
	"ILOSC_MAGAZYN" NUMBER NOT NULL ENABLE, 
	"STATUS_PRODUKTU" VARCHAR2(20) NOT NULL ENABLE, 
	"OUTLET" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"ZDJECIE_PRODUKTU" BLOB, 
	"ZDJECIE_PRODUKTU_NAZWA" BLOB, 
	 CONSTRAINT "TOWARY_PK" PRIMARY KEY ("ID_ARTYKULU")
  USING INDEX  ENABLE
   )
/

CREATE TABLE  "DOSTAWCY" 
   (	"NIP" VARCHAR2(13 CHAR) NOT NULL ENABLE, 
	"NUMER_KONTA" VARCHAR2(26 CHAR) NOT NULL ENABLE, 
	"NAZWA_DOSTAWCY" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"LOKALIZACJA" VARCHAR2(45 CHAR) NOT NULL ENABLE, 
	"REGON" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "DOSTAWCY_PK" PRIMARY KEY ("NIP")
  USING INDEX  ENABLE
   )
/

CREATE TABLE  "HTMLDB_PLAN_TABLE" 
   (	"STATEMENT_ID" VARCHAR2(30), 
	"PLAN_ID" NUMBER, 
	"TIMESTAMP" DATE, 
	"REMARKS" VARCHAR2(4000), 
	"OPERATION" VARCHAR2(30), 
	"OPTIONS" VARCHAR2(255), 
	"OBJECT_NODE" VARCHAR2(128), 
	"OBJECT_OWNER" VARCHAR2(128), 
	"OBJECT_NAME" VARCHAR2(128), 
	"OBJECT_ALIAS" VARCHAR2(261), 
	"OBJECT_INSTANCE" NUMBER(*,0), 
	"OBJECT_TYPE" VARCHAR2(128), 
	"OPTIMIZER" VARCHAR2(255), 
	"SEARCH_COLUMNS" NUMBER, 
	"ID" NUMBER(*,0), 
	"PARENT_ID" NUMBER(*,0), 
	"DEPTH" NUMBER(*,0), 
	"POSITION" NUMBER(*,0), 
	"COST" NUMBER(*,0), 
	"CARDINALITY" NUMBER(*,0), 
	"BYTES" NUMBER(*,0), 
	"OTHER_TAG" VARCHAR2(255), 
	"PARTITION_START" VARCHAR2(255), 
	"PARTITION_STOP" VARCHAR2(255), 
	"PARTITION_ID" NUMBER(*,0), 
	"OTHER" LONG, 
	"DISTRIBUTION" VARCHAR2(30), 
	"CPU_COST" NUMBER(*,0), 
	"IO_COST" NUMBER(*,0), 
	"TEMP_SPACE" NUMBER(*,0), 
	"ACCESS_PREDICATES" VARCHAR2(4000), 
	"FILTER_PREDICATES" VARCHAR2(4000), 
	"PROJECTION" VARCHAR2(4000), 
	"TIME" NUMBER(*,0), 
	"QBLOCK_NAME" VARCHAR2(128)
   )
/

CREATE TABLE  "KATEGORIA" 
   (	"KATEGORIA" NUMBER(*,0) NOT NULL ENABLE, 
	"NAZWA_KATEGORII" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "KATEGORIA_PK" PRIMARY KEY ("KATEGORIA")
  USING INDEX  ENABLE
   )
/

CREATE TABLE  "PRACOWNICY" 
   (	"PESEL" NUMBER(*,0) NOT NULL ENABLE, 
	"NAZWISKO" VARCHAR2(45 CHAR) NOT NULL ENABLE, 
	"IMIE" VARCHAR2(45 CHAR) NOT NULL ENABLE, 
	"STANOWISKO" NUMBER(*,0) NOT NULL ENABLE, 
	"CZAS_PRACY" NUMBER(4,2) NOT NULL ENABLE, 
	"DNI_URLOPU" NUMBER(4,2) NOT NULL ENABLE, 
	"KOD_POCZTOWY" VARCHAR2(6) NOT NULL ENABLE, 
	"MIEJSCOWOSC" VARCHAR2(60) NOT NULL ENABLE, 
	"ULICA" VARCHAR2(60), 
	"NUMER_DOMU" VARCHAR2(10) NOT NULL ENABLE, 
	"WYKORZYSTANY_URLOP" DATE, 
	 CONSTRAINT "PRACOWNICY_PK" PRIMARY KEY ("PESEL")
  USING INDEX  ENABLE
   )
/

CREATE TABLE  "STANOWISKO" 
   (	"ID_STANOWISKA" NUMBER(*,0) NOT NULL ENABLE, 
	"NAZWA" VARCHAR2(45 CHAR) NOT NULL ENABLE, 
	"PLACA" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "STANOWISKO_PK" PRIMARY KEY ("ID_STANOWISKA")
  USING INDEX  ENABLE
   )
/

CREATE TABLE  "SZCZEGOLY_ZAMOWIENIA" 
   (	"ZAMOWIENIE" NUMBER(*,0) NOT NULL ENABLE, 
	"ARTYKUL" NUMBER(*,0) NOT NULL ENABLE, 
	"ILOSC_ZAMOWIONYCH_SZTUK" NUMBER NOT NULL ENABLE, 
	"VAT" NUMBER, 
	"FORMA_ZAMOWIENIA" VARCHAR2(60) NOT NULL ENABLE
   )
/


CREATE TABLE  "SZCZEGOLY_ZAMOWIENIA_DOSTAWCY" 
   (	"ZAMOWIENIE_DOSTAWCA" NUMBER(*,0) NOT NULL ENABLE, 
	"ARTYKUL_DOSTAWCA" NUMBER(*,0) NOT NULL ENABLE, 
	"ILOSC_ZAMOWIONYCH_SZTUK" NUMBER NOT NULL ENABLE, 
	"VAT" NUMBER, 
	"CENA" NUMBER NOT NULL ENABLE
   )
/


CREATE TABLE  "ZAMOWIENIA" 
   (	"ID_ZAMOWIENIA" NUMBER(*,0) NOT NULL ENABLE, 
	"KLIENT" NUMBER(*,0) NOT NULL ENABLE, 
	"NALEZNOSC" NUMBER, 
	"DATA_ZAMOWIENIA" DATE NOT NULL ENABLE, 
	"ZWROT" VARCHAR2(3 CHAR) DEFAULT 'NIE', 
	 CONSTRAINT "ZAMOWIENIA_PK" PRIMARY KEY ("ID_ZAMOWIENIA")
  USING INDEX  ENABLE
   )
/

CREATE TABLE  "ZAMOWIENIA_DOSTAWCY" 
   (	"ID_ZAMOWIENIA_DOSTAWCY" NUMBER NOT NULL ENABLE, 
	"NIP_DOSTAWCY" VARCHAR2(13) NOT NULL ENABLE, 
	"PESEL_PRACOWNIKA" NUMBER(*,0) NOT NULL ENABLE, 
	"NALEZNOSC" NUMBER NOT NULL ENABLE, 
	"DATA_ZAMOWIENIA" DATE NOT NULL ENABLE, 
	 CONSTRAINT "ZAM_DOST_PK" PRIMARY KEY ("ID_ZAMOWIENIA_DOSTAWCY")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "ZAMOWIENIA_DOSTAWCY" ADD CONSTRAINT "ZAMOWIENIADOST_PRACOWNICY_FK" FOREIGN KEY ("PESEL_PRACOWNIKA")
	  REFERENCES  "PRACOWNICY" ("PESEL") ENABLE
/
ALTER TABLE  "ZAMOWIENIA_DOSTAWCY" ADD CONSTRAINT "ZAMOWIENIA_DOSTAWCY_FK" FOREIGN KEY ("NIP_DOSTAWCY")
	  REFERENCES  "DOSTAWCY" ("NIP") ENABLE
/
ALTER TABLE  "ARTYKULY" ADD CONSTRAINT "TOWARY_DOSTAWCY_FK" FOREIGN KEY ("NIP_DOSTAWCY")
	  REFERENCES  "DOSTAWCY" ("NIP") ENABLE
/
ALTER TABLE  "ARTYKULY" ADD CONSTRAINT "TOWARY_KATEGORIA_FK" FOREIGN KEY ("KATEGORIA")
	  REFERENCES  "KATEGORIA" ("KATEGORIA") ENABLE
/
ALTER TABLE  "SZCZEGOLY_ZAMOWIENIA_DOSTAWCY" ADD CONSTRAINT "S_ARTYKULY_DOST_FK" FOREIGN KEY ("ARTYKUL_DOSTAWCA")
	  REFERENCES  "ARTYKULY" ("ID_ARTYKULU") ENABLE
/
ALTER TABLE  "SZCZEGOLY_ZAMOWIENIA_DOSTAWCY" ADD CONSTRAINT "S_ZAMOWIENIA_DOST_FK" FOREIGN KEY ("ZAMOWIENIE_DOSTAWCA")
	  REFERENCES  "ZAMOWIENIA_DOSTAWCY" ("ID_ZAMOWIENIA_DOSTAWCY") ENABLE
/
ALTER TABLE  "ZAMOWIENIA" ADD CONSTRAINT "ZAMOWIENIA_KLIENCI_FK" FOREIGN KEY ("KLIENT")
	  REFERENCES  "KLIENCI" ("ID_KLIENTA") ENABLE
/
ALTER TABLE  "SZCZEGOLY_ZAMOWIENIA" ADD CONSTRAINT "ARTYKULY_FK" FOREIGN KEY ("ARTYKUL")
	  REFERENCES  "ARTYKULY" ("ID_ARTYKULU") ENABLE
/
ALTER TABLE  "SZCZEGOLY_ZAMOWIENIA" ADD CONSTRAINT "ZAMOWIENIA_FK" FOREIGN KEY ("ZAMOWIENIE")
	  REFERENCES  "ZAMOWIENIA" ("ID_ZAMOWIENIA") ENABLE
/

ALTER TABLE  "PRACOWNICY" ADD CONSTRAINT "PRACOWNICY_STANOWISKO_FK" FOREIGN KEY ("STANOWISKO")
	  REFERENCES  "STANOWISKO" ("ID_STANOWISKA") ENABLE
/



