prompt --application/pages/page_00036
begin
--   Manifest
--     PAGE: 00036
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.10.07'
,p_release=>'22.2.0'
,p_default_workspace_id=>25142937697737223804
,p_default_application_id=>23067
,p_default_id_offset=>0
,p_default_owner=>'WKSP_MYSZARD'
);
wwv_flow_imp_page.create_page(
 p_id=>36
,p_name=>'Wyszukanie Artykulow'
,p_alias=>'WYSZUKANIE-ARTYKULOW1'
,p_step_title=>'Wyszukanie Artykulow'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'18'
,p_last_updated_by=>'JONASZ2105@GMAIL.COM'
,p_last_upd_yyyymmddhh24miss=>'20230111231123'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(39155944803144334506)
,p_plug_name=>'Wyszukanie Artykulow'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(25195855485177863063)
,p_plug_display_sequence=>10
,p_query_type=>'SQL'
,p_plug_source=>'select "ID_ARTYKULU","KATEGORIA","NAZWA_ARTYKULU","PRODUCENT","NIP_DOSTAWCY","CENA_JEDNOSTKOWA","ILOSC_MAGAZYN","STATUS_PRODUKTU","OUTLET",sys.dbms_lob.getlength("ZDJECIE_PRODUKTU")"ZDJECIE_PRODUKTU",sys.dbms_lob.getlength("ZDJECIE_PRODUKTU_NAZWA")"Z'
||'DJECIE_PRODUKTU_NAZWA"from "ARTYKULY"'
,p_plug_source_type=>'NATIVE_IR'
,p_prn_page_header=>'Wyszukanie Artykulow'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(39155944972593334506)
,p_name=>'Wyszukanie Artykulow'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_base_pk1=>'ID_ARTYKULU'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'C'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_detail_link=>'f?p=&APP_ID.:37:&APP_SESSION.::&DEBUG.:RP:P37_ID_ARTYKULU:\#ID_ARTYKULU#\'
,p_detail_link_text=>'<span aria-label="Edit"><span class="fa fa-edit" aria-hidden="true" title="Edit"></span></span>'
,p_owner=>'MACIEKZAK550@GMAIL.COM'
,p_internal_uid=>39155944972593334506
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(39155945308984334507)
,p_db_column_name=>'ID_ARTYKULU'
,p_display_order=>0
,p_column_identifier=>'A'
,p_column_label=>'Id Artykulu'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(39155945791362334508)
,p_db_column_name=>'KATEGORIA'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Kategoria'
,p_column_type=>'STRING'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_rpt_named_lov=>wwv_flow_imp.id(25840906826090628125)
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(39155946157820334508)
,p_db_column_name=>'NAZWA_ARTYKULU'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'Nazwa Artykulu'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(39155946516600334509)
,p_db_column_name=>'PRODUCENT'
,p_display_order=>4
,p_column_identifier=>'D'
,p_column_label=>'Producent'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(39155946959181334509)
,p_db_column_name=>'NIP_DOSTAWCY'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Nip Dostawcy'
,p_column_type=>'STRING'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_rpt_named_lov=>wwv_flow_imp.id(25840908389612628126)
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(39155947365030334509)
,p_db_column_name=>'CENA_JEDNOSTKOWA'
,p_display_order=>6
,p_column_identifier=>'F'
,p_column_label=>'Cena Jednostkowa'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'999G999G999G999G999G999G999G999G999G990'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(39155947701811334509)
,p_db_column_name=>'ILOSC_MAGAZYN'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Ilosc Magazyn'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'990'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(39155948173563334510)
,p_db_column_name=>'STATUS_PRODUKTU'
,p_display_order=>8
,p_column_identifier=>'H'
,p_column_label=>'Status Produktu'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(39155948558290334510)
,p_db_column_name=>'OUTLET'
,p_display_order=>9
,p_column_identifier=>'I'
,p_column_label=>'Outlet'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(39155948985173334510)
,p_db_column_name=>'ZDJECIE_PRODUKTU'
,p_display_order=>10
,p_column_identifier=>'J'
,p_column_label=>'Zdjecie Produktu'
,p_allow_sorting=>'N'
,p_allow_filtering=>'N'
,p_allow_highlighting=>'N'
,p_allow_ctrl_breaks=>'N'
,p_allow_aggregations=>'N'
,p_allow_computations=>'N'
,p_allow_charting=>'N'
,p_allow_group_by=>'N'
,p_allow_pivot=>'N'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'LEFT'
,p_format_mask=>'DOWNLOAD:ARTYKULY:ZDJECIE_PRODUKTU:ID_ARTYKULU::::::attachment::'
,p_tz_dependent=>'N'
,p_rpt_show_filter_lov=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(39155949366095334511)
,p_db_column_name=>'ZDJECIE_PRODUKTU_NAZWA'
,p_display_order=>11
,p_column_identifier=>'K'
,p_column_label=>'Zdjecie Produktu Nazwa'
,p_allow_sorting=>'N'
,p_allow_filtering=>'N'
,p_allow_highlighting=>'N'
,p_allow_ctrl_breaks=>'N'
,p_allow_aggregations=>'N'
,p_allow_computations=>'N'
,p_allow_charting=>'N'
,p_allow_group_by=>'N'
,p_allow_pivot=>'N'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'LEFT'
,p_format_mask=>'DOWNLOAD:ARTYKULY:ZDJECIE_PRODUKTU_NAZWA:ID_ARTYKULU::::::attachment::'
,p_tz_dependent=>'N'
,p_rpt_show_filter_lov=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(39156440818476344658)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'391564409'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'ID_ARTYKULU:KATEGORIA:NAZWA_ARTYKULU:PRODUCENT:NIP_DOSTAWCY:CENA_JEDNOSTKOWA:ILOSC_MAGAZYN:STATUS_PRODUKTU:OUTLET:ZDJECIE_PRODUKTU:ZDJECIE_PRODUKTU_NAZWA'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(39155951506899334512)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(25195877711652863073)
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(25195361961967863016)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_imp.id(25195939834312863106)
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(39155949821640334511)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(39155944803144334506)
,p_button_name=>'CREATE'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_imp.id(25195938296627863106)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Create'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_redirect_url=>'f?p=&APP_ID.:37:&APP_SESSION.::&DEBUG.:37::'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(39155950169605334511)
,p_name=>'Edit Report - Dialog Closed'
,p_event_sequence=>10
,p_triggering_element_type=>'REGION'
,p_triggering_region_id=>wwv_flow_imp.id(39155944803144334506)
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'apexafterclosedialog'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(39155950694583334511)
,p_event_id=>wwv_flow_imp.id(39155950169605334511)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_imp.id(39155944803144334506)
);
wwv_flow_imp.component_end;
end;
/
